### ISSUE TITLE
Possibility to specify output filename

### ISSUE THREAD

**Issue by gerbsen** [psteinb/covid19-curve-your-city#16]
While (automatically) generating output for multiple cities/regions it would be extremely helpful to provide a output file name. This would also help to save the files over time.

**Comment by psteinb** [comment]
I had a similar idea. How about the following, if the input filename is `www_dresden.png`, the fit generates
`www_dresden_plus7_de.png` and `www_dresden_plus7_en.png`?

**Comment by gerbsen** [comment]
I would like to inject the filename for bash automation, e.g. add date or other paramters of the fit. also what does plus7 stand for?

**Comment by psteinb** [comment]
I see, well specifying the output filename will always be possible. For me, the default outputname needs to be chosen carefully.

plus7 = prediction to 7 days into the future

**Comment by psteinb** [comment]
BTW, the current version already contains a flag for the output file name. Have a look at the help with `-h`. Effectively, You can use `-o` and the output path, say add `-o test.png`. This will generate `de_test.png` and `en_test.png`. Is that what you are looking for?

**Comment by psteinb** [comment]
@gerbsen if the above does not meet your needs, please reopen this issue.
