### ISSUE TITLE
fehlerhafte Skalierung de_plus7.png seit 11.4.

### ISSUE THREAD

**Issue by RickorDD** [psteinb/covid19-curve-your-city#31]
Die Grafik de_plus7.png (linear) zeigt am 11.4.  "-1000" am 12.4. "-2000" ab.

![de_plus7](https://user-images.githubusercontent.com/6922544/79097981-4a4bc200-7d61-11ea-9edb-dabf444549c6.png)

**Comment by psteinb** [comment]
Hi,
ja, das ist zu erwarten. Der Fit ist wirklich sher einfach gestrickt und zieht bspw. die Begrenzung bei 0 nicht in Betracht. Das
wirkt sich auf die Fehlerabschätzung ab.
Danke für den Issue. Bitte wiederöffnen bei Bedarf.
