### ISSUE TITLE
workflow actions will be disabled 

### ISSUE THREAD

**Issue by vv01f** [psteinb/covid19-curve-your-city#33]
@psteinb 
… after 60 days

so you may wish to re-enable manually in case you want it to continue.

**Comment by psteinb** [comment]
let me see if I can find how to do that.

**Comment by psteinb** [comment]
Which exactly will it stop working?

**Comment by vv01f** [comment]
[the](url) one on [my fork](https://github.com/vv01f/covid19-curve-your-city/actions) was disabled and I had to re-enable manually. 

citation from an email (from noreply@github.com) I received:

> Scheduled workflows are disabled automatically after 60 days of repository inactivity.
> 
> If you would like the "Data Provider" workflow to continue running, click the link bellow.
> 
> https://github.com/vv01f/covid19-curve-your-city/actions?query=workflow%3A%22Data+Provider%22

… so I manually walked in the repo manually and found a button re-enable.

> Which exactly will it stop working?

I guess any after inactivity grace period of the repo. 

I fail to find that on github docs, but it's also reported [elsewhere](https://discourse.julialang.org/t/compathelper-workflows-disabled-after-60-days-of-inactivity/48870) and [documentation talks of dropping some files after 90 days](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-repository) – worst case on public free repos.

**Comment by psteinb** [comment]
Thanks for providing these details. I'll be on my guard.
